### ISSUE TITLE
Exploring

### ISSUE THREAD

**Issue by enzyme69** [zeffii/b3d_osc_panel#3]
Zeff, I could not find what so called Text Editor side panel. I am using MacOS. 

I have installed python-osc module and your Add-On. And see no changes. 

Will read the documentation again... maybe I missed something.

**Comment by enzyme69** [comment]
I installed this into my conda pip install:
https://pypi.python.org/pypi/python-osc

Then copy paste into Blender site-packages.

**Comment by enzyme69** [comment]
Just realized CTRL+F opens up hidden side panel... who would have thought??
https://developer.blender.org/T35475

Ok now I can see the panel thing, will follow the documentation.

**Comment by enzyme69** [comment]
I tried once and seems to be working, but no effect on 'Cube' whatsoever. Is it possible to actually see all the data coming in or out? I keep guessing which path, but I think TouchOSC  has /xy or something I need to go back to Scratch server.

Second time failed:
![screen shot 2016-08-23 at 18 10 15](https://cloud.githubusercontent.com/assets/3952687/17884705/075a3d6c-695d-11e6-9747-27a72f25c9bf.png)

**Comment by zeffii** [comment]
figure out which path and port your touchOSC is sending on.

you might have to close/open blender more often during the testing of this thing..

**Comment by zeffii** [comment]
and never type in the first slash..(I automatically add it)

``` python
"circle"  ->   "/circle"
"fx/node1/boom" -> "/fx/node1/boom"
```

no need for quotemarks either.

**Comment by zeffii** [comment]
don't press start until you've set up all your paths

**Comment by enzyme69** [comment]
yes, still trying to find which path the data is sending in. so far I got Blender crashing, firstly because I do not have modal, and another time it crashes right away because maybe the ip address is wrong.

what is my computer IP address?

if using Scratch Bridge OSC, I can see the data coming in from my iPad:
![screen shot 2016-08-23 at 18 22 14](https://cloud.githubusercontent.com/assets/3952687/17885021/9c174ec6-695e-11e6-93e0-97f60dc2c22e.png)

Maybe I have 2 server running and Blender crashes, I will close the Bridge now... testing again.

**Comment by zeffii** [comment]
i think when you are using an app like Scratch to bridge the external device, then b3d_osc_panel will be only looking on 127.0.0.1 and by the looks of it port 9000, and anything coming from the TouchOSS will be path prefixed by `/scratch/`.

If your touchOSC is sending to path `/ACCXYZ`, then I think scratch resends that as `/SCRATCH/ACCXYZ` on 127.0.0.1 port 9000.

not sure if the paths are case sensitive.

**Comment by enzyme69** [comment]
so far:
1) still not sure if the path is correct
/ACCXYZ and need do_ACCXYZ, but not sure if value is coming in. I tried print(value) nothing
/3/XY is this mean I need do_3_XY in text?

2) so far cannot see any input

I will try again with Bridge OSC on, maybe you are right, it will pipe it into scratch.

One second....

**Comment by zeffii** [comment]
| path | function file |
| --- | --- |
| /circle | do_circle |
| /scratch/accxyz | do_scratch/accxyz |

**Comment by zeffii** [comment]
btw you are right, if a function file is being called then `print(value)` will print the incoming value to console/terminal

**Comment by enzyme69** [comment]
![screen shot 2016-08-23 at 18 42 37](https://cloud.githubusercontent.com/assets/3952687/17885636/6d85d912-6961-11e6-99aa-68c17729bf5b.png)

cannot see any reaction yet...

**Comment by zeffii** [comment]
![gifwee](https://cloud.githubusercontent.com/assets/619340/17885713/b9b4833a-691e-11e6-957a-7a0fa92fc588.gif)

**Comment by zeffii** [comment]
`print(value)` would print to std out, so if you aren't starting Blender from a terminal you might not see any print outs..

**Comment by enzyme69** [comment]
Yes, I open Blender from terminal. Still not seeing anything, maybe I didn't type correct IP. Btw, I keep changing IP address, but it is not updating in Terminal.

![screen shot 2016-08-23 at 19 07 19](https://cloud.githubusercontent.com/assets/3952687/17886380/dbb12ace-6964-11e6-966b-ec9133bcd0c8.png)

As soon as I see something happens, I will let you know.

Glad it is working on your side, Zeffii! This is awesome, can't wait to see it working with AN or SV.

**Comment by zeffii** [comment]
don't press start until after you've added paths..  I should probably disble the start button until the user has added at least one path..

**Comment by zeffii** [comment]
if you see the message 'already active' then you should restart Blender. (i haven't worked out how to start + stop yet)

**Comment by enzyme69** [comment]
ok good sign, it seems to work and I was excited and I stopped it and start again and it stops working. 

Yes, I keep seeing "already active", will restart Blender and this should work. Apparently it was the address and port thing I was getting it wrong.

It works after:
1) I use the IP that is showing at OSC Bridge
2) Port is matching the TouchOSC 
3) I don't need to use /scratch

💃 This is exciting!

**Comment by zeffii** [comment]
I will try to address the start/stop failure. [Check for updates](https://github.com/zeffii/b3d_osc_panel/commits/master)

**Comment by enzyme69** [comment]
Ok cheers! 

Btw, I just tried Motion Capturing the motion while playback is running and it does not work. Normally I move the Object using 3D view handle and it records the motion of my mouse. Somewhat it does not like it.

**Comment by enzyme69** [comment]
I am updating...

**Comment by zeffii** [comment]
yeah, motion capturing this is untested.. maybe i need to automatic keyframing..

**Comment by zeffii** [comment]
just to be clear here 

**do_scratch/accxyz** could look like this

``` python
c = bpy.data.objects['Cube']
c.location.z =  value

```

**Comment by enzyme69** [comment]
Ok reporting:
When address already in use by OSC Scratch Bridge, Blender crashes. No wonder. 

btw sometimes the data is like this, multiple data:
accxyz/1
accxyz/2
accxyz/3

so I need each separate:
do_accxyz/1
do_accxyz/2
do_accxyz/3

just to plugin to the cube pos xyz right? testing it now, restarting Blender.

**Comment by zeffii** [comment]
btw , the automatic keyframing (Motion Capture) only works because of the UI interaction with the Transform widget (unless i'm mistaken). Because we are modifying values directly we (unfortunatly in this scenario) are bypassing that convenient feature.

This doesn't mean that it can't be done..

**Comment by zeffii** [comment]
ah.. so that is a tricky thing, separating / combining values. technically not difficult, but implementing it in a user friendly way will require some braintime

**Comment by enzyme69** [comment]
still getting "already active". restarting Blender.

ok the auto-keyframing will not work that way, so I will try with node 🍡

**Comment by zeffii** [comment]
I will tell you when the 'already active' is fixed. until then..get ready to restart blender a lot :)

**Comment by enzyme69** [comment]
Ok no problem! Very happy that this works. Can try with my procedural flipping thing. Woohoo!

**Comment by zeffii** [comment]
early stages yet!

**Comment by enzyme69** [comment]
![capture_an_osc](https://cloud.githubusercontent.com/assets/3952687/17888306/ad4e313c-696d-11e6-9b6f-9d50026ea144.gif)

Aha, I see it's outputting value to console as well.

This makes my day!

**Comment by zeffii** [comment]
hehe cool! 
btw, the combining of values may be tricky,
i might be able to set up a `osc_combiner` function file which might let us, do something like

``` python
combiner_dict = {
   ("/val1/x", "/val1/y", "/val1/z") : "/gen_xyz"
}
```

this dict would be filled out to combine values, and send all three values at once as a new "osc path" (/gen_xyz), which could send the last three received values of ("/val1/x", "/val1/y", "/val1/z").

no ETA...but that's what i'm thinking about ..  

not even sure this is needed?

**Comment by enzyme69** [comment]
Let me think... in Scratch, each value going in is already filtered by Scratch OSC Bridge, so every data path is separate. Kind of like current implementation as Text. But it has node like dropdown.

I guess it should be okey like this, I just need to use multiple text and switching back and forth. I want to test the limit.

Maybe can use Script node of Sverchok, or Animation Nodes.

1) Provide list of path
2) Generate Text based on list
3) Pass value to attribute.

I will test the OSC interface first. The app I am using is Touch OSC, it comes with so many templates of Knob, Fader, toggle.

This is really cool, it's always realtime as long my wifi is fast enough. I can even work on other things in Blender, while adjusting this. I can control lights too. Totally new experience 🎯 It's probably can be done using BGE? But nah, I like it like this~

**Comment by zeffii** [comment]
A few things
- i'm not sure the settings get stored in the .blend (probably not)
- could do with a presets feature
- could do with loading presets from a file (probably easiest to implement)

**Comment by enzyme69** [comment]
I just tested:
- Yes the settings get stored with the blend! 👍 
- Preset would be cool and a way to modify the default IP Address
- What would be even cooler is if we have this as a node. Script node that is :D But I tested using AN just now and it works great! AN can drive Cycles Material and hook here and there... I make this video (uploading now....)

**Comment by zeffii** [comment]
recent update fixes the start-end buttons :)

**Comment by enzyme69** [comment]
In Processing, I can read the /accxyz as fff, three floating values.

Wonder how to read it in BlenderOSC? I tried print(value[0]) didn't work

**Comment by enzyme69** [comment]
And... what's the best way to store value and pass it. Let say if I use SuperCollider and passing "message", String, how do I pass it down?

So far I am doing it like below:

bpy.data.node_groups["NodeTree"].nodes["Data Input"].inputs[0].value = value

does not look elegant....

I think what would be interesting is to pass data value to make sound. will test soon.

**Comment by zeffii** [comment]
communicating lists (comma separated values) should be fine, i'll have a look at that - hopefully a quick fix.

regarding the inelegance of 

``` python
bpy.data.node_groups["NodeTree"].nodes["Data Input"].inputs[0].value = value
```

well, obviously that's not the prettiest, but you can't expect code to always be like writing shakespearian prose.

I would write something like:

``` python
ng = bpy.data.node_groups["NodeTree"]
nodes = ng.nodes
data_node = nodes.["Data Input"]
data_node.inputs[0].value = value
```

**Comment by zeffii** [comment]
it could be possible to implement an aliases file so that you only need to create aliases in one file and then only do something like 

``` python
data_node.inputs[0].value = value
```

but I haven't decided on all of this, and don't want to code something what will get replaced soon anyway.

**Comment by enzyme69** [comment]
The error was:

``` traceback
Exception happened during processing of request from ('192.168.1.100', 59914)
Traceback (most recent call last):
  File "python/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "python/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "python/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "python/lib/python3.5/site-packages/pythonosc/osc_server.py", line 91, in handle
    _call_handlers_for_packet(self.request[0], self.server.dispatcher)
  File "python/lib/python3.5/site-packages/pythonosc/osc_server.py", line 74, in _call_handlers_for_packet
    handler.callback(timed_msg.message.address, *timed_msg.message)
TypeError: general_handler() takes 2 positional arguments but 4 were given
```

**Comment by enzyme69** [comment]
I did manage to have text sent from Super Collider to Blender and display it :) Proud.

Things I still have not quite clear idea:
1) To see "all" the message path and value, especially multiple values
2) Monitoring all the data

Probably need a way to hook this up to AN/SV Script node.

**Comment by zeffii** [comment]
That's a nice / useful error! I know what to do but i've been concentrating on other things.

For the moment you could send lists as text and then eval then 

```
>>> my_list = eval("[23, 45, 56, 23, 45]")
>>> my_list
[23, 45, 56, 23, 45]
```

not ideal, but it's simple and works.

**Comment by zeffii** [comment]
the `pythonosc` library is itself not extensively documented on a high level, so I'll end up reading though the code to make sense of it. Also.. i'm finding very few examples of usage / non of dealing with multi-value 'bundles'.

**Comment by zeffii** [comment]
i'll probably write the `general_handler()` as

``` python
def general_handler(*args):
    num_args = len(args)
    if num_args == 2:
      do normal
    elif num_args == 3:
      do something else
    elif num_args == 4:
      do something else
    else:
      wat.
```

**Comment by enzyme69** [comment]
It's been working great so far!

I manage to pipe in some messages from the TouchOSC app data into Blender. 

My task:
Try to pipe in realtime audio using ChucK or Processing or Super Collider. Something just to trigger sound. This should be simple enough before I do LIVE NODING about it. Which "interface" is best do you reckon? I am still familiarizing myself with OSC.

I manage to hook up the accxyz message to Camera rotation :) for example.

Currently:
ZOSC => locator xyz via bpy => AN rotation convert.

Exploration Questions:
1) With "do_stuff" doing bpy, is there a more elegant way to get the input like to Sverchok or AN via Script node?
2) I realized the value coming in is jittering, if I were to use this as camera, I need a way to "stabilize". Any pointer on this? Maybe Math formulat?
3) Is the data type does not matter in this case?

**Comment by enzyme69** [comment]
EDIT-
https://gist.github.com/zeffii/88238fcf11c8e38e720feeb9f835d98c crash dump as gist please in future.

**Comment by zeffii** [comment]
I am surprised it hasn't crashed sooner, unfortunately the crash report doesn't help me identify a cause or explain what was happening at the time.

The OSC panel uses multithreading to act on new incoming messages, this feature is known to have problematic side effects if two or more threads attempt to update the same bpy property simultaneously  - it may effect updating any number of bpy objects / python objects simultaneously. Remember AN and SV are essentially single threaded Python scripts on steroids - and are limited by that issue.

Stabilisation would be a post processing step, first get the keyframes, then smooth them over a wide time interval like 1 second. There are some options for near-realtime smoothing called 'transient compressors', but that's not implemented.

**Comment by zeffii** [comment]
If i can get it to get all messages received every `1/n` seconds, and spit out the last (or middle) message for each `/path`, then the operator could run at `1/n` and avoid the possibility of crashes due to accessing multiple bpy/python things simultaneously.. then it would be possible to execute the handler functions in a sequence rather than _parallel_ (which is what's happening at the moment).

**Comment by zeffii** [comment]
> Try to pipe in realtime audio using ChucK, Processing or SuperCollider

my point was that you must process the audio in those environment and crunch down the incoming signal in those apps to a number (or list of frequency amplitudes for example) that can be transmitted far less often, like 24hz (or framerate), there's no reason to transmit more data than will be handled.

**Comment by zeffii** [comment]
i've changed the implementation, nothing much should change on the outside, but i've limited the rate temporarily to 10 updates per second. An update means it will loop through all paths that have values and that haven't been handled yet, it will handle those, and thereby clearing a queue.

**Comment by zeffii** [comment]
https://github.com/zeffii/b3d_osc_panel/tree/honolulu ( a different branch )

**Comment by enzyme69** [comment]
So I go to different branch and use that one? I am currently testing FaceOSC with Blender.

**Comment by enzyme69** [comment]
so strange, I keep getting:
already active
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.77/scripts/addons/b3d_osc_panel-honolulu/**init**.py", line 188, in execute
    self.event_dispatcher(context, self.mode)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.77/scripts/addons/b3d_osc_panel-honolulu/**init**.py", line 183, in event_dispatcher
    osc_statemachine['server'].shutdown()
KeyError: 'server'

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by enzyme69** [comment]
ok the Honolulu branch is updating every 10 clicks... still working luckily.

**Comment by enzyme69** [comment]
I went back to previous version because it is faster to update.

**Comment by zeffii** [comment]
ok if honolulu isn't fast enough this is the line you have to change to a lower value

```
speed = FloatProperty(default=0.1)
```

set it to 0.02 and tell me if it's fast enough.. or set it lower until it works for you.. 

I can add this to the UI (no reason not to), but won't have time for a while

**Comment by enzyme69** [comment]
Thanks so much Sir Zeff!

---
- Jimmy Gunawan
  http://blendersushi.blogspot.com.au
  http://mayaspiral.blogspot.com.au
  http://houdoodles.blogspot.com.au
  http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
there's a modified version now: https://github.com/zeffii/b3d_osc_panel/tree/tahiti  you can update the speed. (you do need to stop/start if you want to change the speed.. that's not something that can be changed)
