### ISSUE TITLE
Sending Messages out?

### ISSUE THREAD

**Issue by enzyme69** [zeffii/b3d_osc_panel#6]
Hi Zeffii,

Is there any chance to have this add-on to also output or sending message from specific port? I am trying to make Blender to work with ChucK OSC.

Seems to work with AddOSC, but AddOSC has limitation: cannot take and send multiple data...

Thanks~

**Comment by zeffii** [comment]
please try the `tahiti` branch, with the `messages p/sec slider` :)

sending OSC is not implemented, but is the easier of OSC features.  Most of the code in the [Simple Client example](https://pypi.python.org/pypi/python-osc) can be hidden away, simplified even further to

_send/filter.py_  

```
msg = {'address'='/filter', 'content'=your_variable}
```

but no ETA on this.. it is not high on my todo

```
```

**Comment by enzyme69** [comment]
Oh ok, there is "tahiti" branch too? Will check. Thanks~

Now, I just need to setup ChucK to listen properly using multiple shreds... challenging but somewhat fun.

**Comment by zeffii** [comment]
yes, https://github.com/zeffii/b3d_osc_panel/issues/3#issuecomment-247601077 (3 days ago)

**Comment by enzyme69** [comment]
Ok, great I think it is working, I copy paste the script to send multiple message inside the loop :) I am using Script node.

Interesting stuff.
