### ISSUE TITLE
QUESTION: Data streaming in from OSC but not updating

### ISSUE THREAD

**Issue by enzyme69** [zeffii/b3d_osc_panel#8]
Probably a question need to be directed to Sverchok, but since you probably know what's going on:

![screen shot 2016-10-31 at 18 05 28](https://cloud.githubusercontent.com/assets/3952687/19846593/d2934f10-9f94-11e6-9bac-627d146236ac.png)

I have this FaceOSC doing face detection in realtime. I am piping in the data using Objects In Matrix, but the position of Matrix does not seem to update in the viewer.

**Comment by zeffii** [comment]
no idea, probably the matrices aren't being updated at all by faceOSC. They look like vertex-objects, where only the single vertex location is modified over time.

**Comment by zeffii** [comment]
test this by using the console to see the matrix for one of the objects at frame 10 then again at frame 120. (pick an object that moves a lot )

**Comment by enzyme69** [comment]
I knew the issue will post at Sverchok Github. Cheers Z!
